### ISSUE TITLE
v8.5 bugs

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/emoncms#311]
A few bugs noticed following a clean git install of v8.4 switched to v8.5 branch.
1. **Mobile drop down menu**  when users are switching from any of the main menu items (Inputs, Feeds, Dashboard etc) to an 'app' sub menu, the menu works fine, however if you try to switch from one 'app' submenu to another submenu item ('My Electric' to 'My Solar'), then the main dropdown menu does not collapse. Bug apparent on Android phone, iPhone & iPad.
2. **My Electric** 'USE TODAY' constantly displays 0.0 kWh and does not increment throughout the day. The graph displays the correct data columns for the preceding days. The source feed is PHPFINA which increments as expected.
3. The **branch switch** from v8.4 to v8.5 did not go as expected, as I ran the 'Admin>Update Database' which appeared successful, but when I ran it again, it again invited me to update the db. This repeated over and over. I then checked 'Account>Timezone' which was a blank text box with no data within. I checked my emoncms/mysql user permissions which were already set to GRANT ALL. Eventually resolved by logging into mysql (using emoncms user login) and running the db update manually;
    mysql> ALTER TABLE `users` MODIFY `timezone` VARCHAR( 64 ) DEFAULT 'UTC';  
Paul

**Comment by chaveiro** [comment]
No 3 fixed here: https://github.com/chaveiro/emoncms/commit/cd73f08504a718da14abc92d6951d96b7653d9aa

**Comment by TrystanLea** [comment]
Thanks Chaveiro, I've copied your fix over to the v8.5 branch too for bug 3. Thanks Paul!

**Comment by Paul-Reed** [comment]
A quick response Chaveiro, thanks.   
I've added a few more...   
1. ***Mobile drop down menu*** when users are switching from any of the main menu items (Inputs, Feeds, Dashboard etc) to an 'app' sub menu, the menu works fine, however if you try to switch from one 'app' submenu to another submenu item ('My Electric' to 'My Solar'), then the main dropdown menu does not collapse. Bug apparent on Android phone, iPhone & iPad.
2. ***My Electric 'USE TODAY'*** constantly displays 0.0 kWh and does not increment throughout the day. The graph displays the correct data columns for the preceding days. The source feed is PHPFINA which increments as expected.
3. When viewing feed data via mobile devices a ***'Undefined offset error'*** message appears at the top of the page - [see screenshot](http://openenergymonitor.org/emon/node/10381#comment-29047)
4. Again, only on mobiles... the ***'My Solar' app does not format well*** and the graph shrinks to the left instead of full width - [see screenshot](http://openenergymonitor.org/emon/node/10381#comment-29000)   
Paul

**Comment by TrystanLea** [comment]
Hello Paul, mysolar resizes much better now, although still not perfect.

**Comment by Paul-Reed** [comment]
Are there any updates to the bugs listed 29th March above.

Thanks

Paul

**Comment by chaveiro** [comment]
Are this issues fixed on 9.2 ?

**Comment by Paul-Reed** [comment]
Now fixed
